version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: secureartifact-mongo
    restart: always
    volumes:
      - mongo_data:/data/db

backend:
  build: ./backend
  image: secureartifact-backend
  container_name: secureartifact-backend
  restart: always
  env_file:
    - ./backend/.env
  ports:
    - "5000:5000"
  depends_on:
    - mongo

frontend:
  build: ./frontend
  image: secureartifact-frontend
  container_name: secureartifact-frontend
  restart: always
  ports:
    - "3000:80"
  depends_on:
    - backend

  # backend:
  #   build: ./backend
  #   container_name: secureartifact-backend
  #   restart: always
  #   env_file:
  #     - ./backend/.env
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - mongo

  # frontend:
  #   build: ./frontend
  #   container_name: secureartifact-frontend
  #   restart: always
  #   ports:
  #     - "3000:80"
  #   depends_on:
  #     - backend

volumes:
  mongo_data: