name: SecureArtifact DevSecOps Pipeline

on:
  push:
    branches: [ main ]

jobs:
  secure-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # -------------------------------
      # Dependency Security Scan
      # -------------------------------
      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Run Backend Dependency Audit (Fail on High)
        run: |
          cd backend
          npm audit --audit-level=high

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Run Frontend Dependency Audit (Fail on High)
        run: |
          cd frontend
          npm audit --audit-level=high

      # -------------------------------
      # Docker Build
      # -------------------------------
      - name: Build Docker Images
        run: docker compose build

            # -------------------------------
      # Container Security Scan (Official Trivy Action)
      # -------------------------------
      - name: Scan Backend Image
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: secureartifact-backend
          severity: CRITICAL
          exit-code: 1

      - name: Scan Frontend Image
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: secureartifact-frontend
          severity: CRITICAL
          exit-code: 1