name: SecureArtifact DevSecOps Pipeline

on:
  push:
    branches: [ main ]

jobs:
  secure-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # -------------------------------
      # Dependency Security Scan
      # -------------------------------
      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Run Backend Dependency Audit (Fail on High)
        run: |
          cd backend
          npm audit --audit-level=high

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Run Frontend Dependency Audit (Fail on High)
        run: |
          cd frontend
          npm audit --audit-level=high

      # -------------------------------
      # Docker Build
      # -------------------------------
      - name: Build Docker Images
        run: docker compose build

      # -------------------------------
      # Install Trivy
      # -------------------------------
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install wget -y
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.50.2_Linux-64bit.deb
          sudo dpkg -i trivy_0.50.2_Linux-64bit.deb

      # -------------------------------
      # Container Vulnerability Scan (STRICT)
      # -------------------------------
      - name: Scan Backend Image (Fail on HIGH/CRITICAL)
        run: |
          trivy image --severity HIGH,CRITICAL --exit-code 1 secureartifact-backend

      - name: Scan Frontend Image (Fail on HIGH/CRITICAL)
        run: |
          trivy image --severity HIGH,CRITICAL --exit-code 1 secureartifact-frontend